# Generated by Django 4.1.2 on 2022-11-02 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_extensionusuario_descripcion_and_more'),
        ('mensajeria', '0002_remove_mensaje_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='mensaje',
            new_name='contenido',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.extensionusuario'),
        ),
    ]
