# Generated by Django 4.1.2 on 2022-10-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
