# Generated by Django 4.1.2 on 2022-10-29 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_persona_fecha_nacimiento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
