# Generated by Django 4.1.2 on 2022-10-28 18:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avanzado', '0004_delete_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('subtitulo', models.CharField(max_length=20)),
                ('contenido', ckeditor.fields.RichTextField(null=True)),
                ('autor', models.CharField(max_length=20)),
                ('fecha_creacion', models.CharField(max_length=20)),
                ('imagen', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
